// Code generated by ent, DO NOT EDIT.

package researchprojectdetailtranslation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the researchprojectdetailtranslation type in the database.
	Label = "research_project_detail_translation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldResearchProjectDetailID holds the string denoting the research_project_detail_id field in the database.
	FieldResearchProjectDetailID = "research_project_detail_id"
	// FieldLanguageCode holds the string denoting the language_code field in the database.
	FieldLanguageCode = "language_code"
	// FieldDetailText holds the string denoting the detail_text field in the database.
	FieldDetailText = "detail_text"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeResearchProjectDetail holds the string denoting the research_project_detail edge name in mutations.
	EdgeResearchProjectDetail = "research_project_detail"
	// EdgeLanguage holds the string denoting the language edge name in mutations.
	EdgeLanguage = "language"
	// LanguageFieldID holds the string denoting the ID field of the Language.
	LanguageFieldID = "code"
	// Table holds the table name of the researchprojectdetailtranslation in the database.
	Table = "research_project_detail_translations"
	// ResearchProjectDetailTable is the table that holds the research_project_detail relation/edge.
	ResearchProjectDetailTable = "research_project_detail_translations"
	// ResearchProjectDetailInverseTable is the table name for the ResearchProjectDetail entity.
	// It exists in this package in order to avoid circular dependency with the "researchprojectdetail" package.
	ResearchProjectDetailInverseTable = "research_project_details"
	// ResearchProjectDetailColumn is the table column denoting the research_project_detail relation/edge.
	ResearchProjectDetailColumn = "research_project_detail_id"
	// LanguageTable is the table that holds the language relation/edge.
	LanguageTable = "research_project_detail_translations"
	// LanguageInverseTable is the table name for the Language entity.
	// It exists in this package in order to avoid circular dependency with the "language" package.
	LanguageInverseTable = "languages"
	// LanguageColumn is the table column denoting the language relation/edge.
	LanguageColumn = "language_code"
)

// Columns holds all SQL columns for researchprojectdetailtranslation fields.
var Columns = []string{
	FieldID,
	FieldResearchProjectDetailID,
	FieldLanguageCode,
	FieldDetailText,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// LanguageCodeValidator is a validator for the "language_code" field. It is called by the builders before save.
	LanguageCodeValidator func(string) error
	// DetailTextValidator is a validator for the "detail_text" field. It is called by the builders before save.
	DetailTextValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the ResearchProjectDetailTranslation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByResearchProjectDetailID orders the results by the research_project_detail_id field.
func ByResearchProjectDetailID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResearchProjectDetailID, opts...).ToFunc()
}

// ByLanguageCode orders the results by the language_code field.
func ByLanguageCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLanguageCode, opts...).ToFunc()
}

// ByDetailText orders the results by the detail_text field.
func ByDetailText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDetailText, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByResearchProjectDetailField orders the results by research_project_detail field.
func ByResearchProjectDetailField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newResearchProjectDetailStep(), sql.OrderByField(field, opts...))
	}
}

// ByLanguageField orders the results by language field.
func ByLanguageField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLanguageStep(), sql.OrderByField(field, opts...))
	}
}
func newResearchProjectDetailStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ResearchProjectDetailInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ResearchProjectDetailTable, ResearchProjectDetailColumn),
	)
}
func newLanguageStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LanguageInverseTable, LanguageFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LanguageTable, LanguageColumn),
	)
}
