name: silan-website
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip>=22.0
  
  # Core dependencies available through conda
  - click>=8.0.0
  - pyyaml>=6.0
  - requests>=2.28.0
  - pillow>=9.0.0
  - jinja2>=3.1.0
  
  # Development tools
  - pytest>=7.0.0
  - black>=22.0.0
  - mypy>=0.991
  - flake8>=5.0.0
  
  # Additional tools
  - git
  - nodejs>=18.0  # For deployment tools (gh-pages, netlify-cli, vercel)
  
  # Dependencies that need to be installed via pip
  - pip:
    - markdown2>=2.4.0
    - python-frontmatter>=1.0.0
    - watchdog>=2.1.0
    - pydantic>=1.10.0
    - rich>=13.0.0
    
    # Optional deployment tools (uncomment if needed)
    # - gh-pages  # For GitHub Pages deployment
    # - netlify-cli  # For Netlify deployment
    # - vercel  # For Vercel deployment