// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"silan-backend/internal/ent/project"
	"silan-backend/internal/ent/projectdetail"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ProjectDetailCreate is the builder for creating a ProjectDetail entity.
type ProjectDetailCreate struct {
	config
	mutation *ProjectDetailMutation
	hooks    []Hook
}

// SetFullDescription sets the "full_description" field.
func (pdc *ProjectDetailCreate) SetFullDescription(s string) *ProjectDetailCreate {
	pdc.mutation.SetFullDescription(s)
	return pdc
}

// SetNillableFullDescription sets the "full_description" field if the given value is not nil.
func (pdc *ProjectDetailCreate) SetNillableFullDescription(s *string) *ProjectDetailCreate {
	if s != nil {
		pdc.SetFullDescription(*s)
	}
	return pdc
}

// SetFeatures sets the "features" field.
func (pdc *ProjectDetailCreate) SetFeatures(s []string) *ProjectDetailCreate {
	pdc.mutation.SetFeatures(s)
	return pdc
}

// SetKeyAchievements sets the "key_achievements" field.
func (pdc *ProjectDetailCreate) SetKeyAchievements(s []string) *ProjectDetailCreate {
	pdc.mutation.SetKeyAchievements(s)
	return pdc
}

// SetChallengesFaced sets the "challenges_faced" field.
func (pdc *ProjectDetailCreate) SetChallengesFaced(s []string) *ProjectDetailCreate {
	pdc.mutation.SetChallengesFaced(s)
	return pdc
}

// SetLessonsLearned sets the "lessons_learned" field.
func (pdc *ProjectDetailCreate) SetLessonsLearned(s []string) *ProjectDetailCreate {
	pdc.mutation.SetLessonsLearned(s)
	return pdc
}

// SetTechnicalOverview sets the "technical_overview" field.
func (pdc *ProjectDetailCreate) SetTechnicalOverview(s string) *ProjectDetailCreate {
	pdc.mutation.SetTechnicalOverview(s)
	return pdc
}

// SetNillableTechnicalOverview sets the "technical_overview" field if the given value is not nil.
func (pdc *ProjectDetailCreate) SetNillableTechnicalOverview(s *string) *ProjectDetailCreate {
	if s != nil {
		pdc.SetTechnicalOverview(*s)
	}
	return pdc
}

// SetInstallationInstructions sets the "installation_instructions" field.
func (pdc *ProjectDetailCreate) SetInstallationInstructions(s string) *ProjectDetailCreate {
	pdc.mutation.SetInstallationInstructions(s)
	return pdc
}

// SetNillableInstallationInstructions sets the "installation_instructions" field if the given value is not nil.
func (pdc *ProjectDetailCreate) SetNillableInstallationInstructions(s *string) *ProjectDetailCreate {
	if s != nil {
		pdc.SetInstallationInstructions(*s)
	}
	return pdc
}

// SetUsageInstructions sets the "usage_instructions" field.
func (pdc *ProjectDetailCreate) SetUsageInstructions(s string) *ProjectDetailCreate {
	pdc.mutation.SetUsageInstructions(s)
	return pdc
}

// SetNillableUsageInstructions sets the "usage_instructions" field if the given value is not nil.
func (pdc *ProjectDetailCreate) SetNillableUsageInstructions(s *string) *ProjectDetailCreate {
	if s != nil {
		pdc.SetUsageInstructions(*s)
	}
	return pdc
}

// SetAPIDocumentation sets the "api_documentation" field.
func (pdc *ProjectDetailCreate) SetAPIDocumentation(s string) *ProjectDetailCreate {
	pdc.mutation.SetAPIDocumentation(s)
	return pdc
}

// SetNillableAPIDocumentation sets the "api_documentation" field if the given value is not nil.
func (pdc *ProjectDetailCreate) SetNillableAPIDocumentation(s *string) *ProjectDetailCreate {
	if s != nil {
		pdc.SetAPIDocumentation(*s)
	}
	return pdc
}

// SetDeploymentNotes sets the "deployment_notes" field.
func (pdc *ProjectDetailCreate) SetDeploymentNotes(s string) *ProjectDetailCreate {
	pdc.mutation.SetDeploymentNotes(s)
	return pdc
}

// SetNillableDeploymentNotes sets the "deployment_notes" field if the given value is not nil.
func (pdc *ProjectDetailCreate) SetNillableDeploymentNotes(s *string) *ProjectDetailCreate {
	if s != nil {
		pdc.SetDeploymentNotes(*s)
	}
	return pdc
}

// SetFutureEnhancements sets the "future_enhancements" field.
func (pdc *ProjectDetailCreate) SetFutureEnhancements(s string) *ProjectDetailCreate {
	pdc.mutation.SetFutureEnhancements(s)
	return pdc
}

// SetNillableFutureEnhancements sets the "future_enhancements" field if the given value is not nil.
func (pdc *ProjectDetailCreate) SetNillableFutureEnhancements(s *string) *ProjectDetailCreate {
	if s != nil {
		pdc.SetFutureEnhancements(*s)
	}
	return pdc
}

// SetTeamMembers sets the "team_members" field.
func (pdc *ProjectDetailCreate) SetTeamMembers(s []string) *ProjectDetailCreate {
	pdc.mutation.SetTeamMembers(s)
	return pdc
}

// SetProjectDuration sets the "project_duration" field.
func (pdc *ProjectDetailCreate) SetProjectDuration(s string) *ProjectDetailCreate {
	pdc.mutation.SetProjectDuration(s)
	return pdc
}

// SetNillableProjectDuration sets the "project_duration" field if the given value is not nil.
func (pdc *ProjectDetailCreate) SetNillableProjectDuration(s *string) *ProjectDetailCreate {
	if s != nil {
		pdc.SetProjectDuration(*s)
	}
	return pdc
}

// SetTargetAudience sets the "target_audience" field.
func (pdc *ProjectDetailCreate) SetTargetAudience(s string) *ProjectDetailCreate {
	pdc.mutation.SetTargetAudience(s)
	return pdc
}

// SetNillableTargetAudience sets the "target_audience" field if the given value is not nil.
func (pdc *ProjectDetailCreate) SetNillableTargetAudience(s *string) *ProjectDetailCreate {
	if s != nil {
		pdc.SetTargetAudience(*s)
	}
	return pdc
}

// SetPerformanceMetrics sets the "performance_metrics" field.
func (pdc *ProjectDetailCreate) SetPerformanceMetrics(m map[string]interface{}) *ProjectDetailCreate {
	pdc.mutation.SetPerformanceMetrics(m)
	return pdc
}

// SetTestingApproach sets the "testing_approach" field.
func (pdc *ProjectDetailCreate) SetTestingApproach(m map[string]interface{}) *ProjectDetailCreate {
	pdc.mutation.SetTestingApproach(m)
	return pdc
}

// SetCreatedAt sets the "created_at" field.
func (pdc *ProjectDetailCreate) SetCreatedAt(t time.Time) *ProjectDetailCreate {
	pdc.mutation.SetCreatedAt(t)
	return pdc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pdc *ProjectDetailCreate) SetNillableCreatedAt(t *time.Time) *ProjectDetailCreate {
	if t != nil {
		pdc.SetCreatedAt(*t)
	}
	return pdc
}

// SetUpdatedAt sets the "updated_at" field.
func (pdc *ProjectDetailCreate) SetUpdatedAt(t time.Time) *ProjectDetailCreate {
	pdc.mutation.SetUpdatedAt(t)
	return pdc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pdc *ProjectDetailCreate) SetNillableUpdatedAt(t *time.Time) *ProjectDetailCreate {
	if t != nil {
		pdc.SetUpdatedAt(*t)
	}
	return pdc
}

// SetID sets the "id" field.
func (pdc *ProjectDetailCreate) SetID(u uuid.UUID) *ProjectDetailCreate {
	pdc.mutation.SetID(u)
	return pdc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (pdc *ProjectDetailCreate) SetNillableID(u *uuid.UUID) *ProjectDetailCreate {
	if u != nil {
		pdc.SetID(*u)
	}
	return pdc
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (pdc *ProjectDetailCreate) SetProjectID(id uuid.UUID) *ProjectDetailCreate {
	pdc.mutation.SetProjectID(id)
	return pdc
}

// SetNillableProjectID sets the "project" edge to the Project entity by ID if the given value is not nil.
func (pdc *ProjectDetailCreate) SetNillableProjectID(id *uuid.UUID) *ProjectDetailCreate {
	if id != nil {
		pdc = pdc.SetProjectID(*id)
	}
	return pdc
}

// SetProject sets the "project" edge to the Project entity.
func (pdc *ProjectDetailCreate) SetProject(p *Project) *ProjectDetailCreate {
	return pdc.SetProjectID(p.ID)
}

// Mutation returns the ProjectDetailMutation object of the builder.
func (pdc *ProjectDetailCreate) Mutation() *ProjectDetailMutation {
	return pdc.mutation
}

// Save creates the ProjectDetail in the database.
func (pdc *ProjectDetailCreate) Save(ctx context.Context) (*ProjectDetail, error) {
	pdc.defaults()
	return withHooks(ctx, pdc.sqlSave, pdc.mutation, pdc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pdc *ProjectDetailCreate) SaveX(ctx context.Context) *ProjectDetail {
	v, err := pdc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pdc *ProjectDetailCreate) Exec(ctx context.Context) error {
	_, err := pdc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pdc *ProjectDetailCreate) ExecX(ctx context.Context) {
	if err := pdc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pdc *ProjectDetailCreate) defaults() {
	if _, ok := pdc.mutation.CreatedAt(); !ok {
		v := projectdetail.DefaultCreatedAt()
		pdc.mutation.SetCreatedAt(v)
	}
	if _, ok := pdc.mutation.UpdatedAt(); !ok {
		v := projectdetail.DefaultUpdatedAt()
		pdc.mutation.SetUpdatedAt(v)
	}
	if _, ok := pdc.mutation.ID(); !ok {
		v := projectdetail.DefaultID()
		pdc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pdc *ProjectDetailCreate) check() error {
	if v, ok := pdc.mutation.ProjectDuration(); ok {
		if err := projectdetail.ProjectDurationValidator(v); err != nil {
			return &ValidationError{Name: "project_duration", err: fmt.Errorf(`ent: validator failed for field "ProjectDetail.project_duration": %w`, err)}
		}
	}
	if v, ok := pdc.mutation.TargetAudience(); ok {
		if err := projectdetail.TargetAudienceValidator(v); err != nil {
			return &ValidationError{Name: "target_audience", err: fmt.Errorf(`ent: validator failed for field "ProjectDetail.target_audience": %w`, err)}
		}
	}
	if _, ok := pdc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProjectDetail.created_at"`)}
	}
	if _, ok := pdc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProjectDetail.updated_at"`)}
	}
	return nil
}

func (pdc *ProjectDetailCreate) sqlSave(ctx context.Context) (*ProjectDetail, error) {
	if err := pdc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pdc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pdc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	pdc.mutation.id = &_node.ID
	pdc.mutation.done = true
	return _node, nil
}

func (pdc *ProjectDetailCreate) createSpec() (*ProjectDetail, *sqlgraph.CreateSpec) {
	var (
		_node = &ProjectDetail{config: pdc.config}
		_spec = sqlgraph.NewCreateSpec(projectdetail.Table, sqlgraph.NewFieldSpec(projectdetail.FieldID, field.TypeUUID))
	)
	if id, ok := pdc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := pdc.mutation.FullDescription(); ok {
		_spec.SetField(projectdetail.FieldFullDescription, field.TypeString, value)
		_node.FullDescription = value
	}
	if value, ok := pdc.mutation.Features(); ok {
		_spec.SetField(projectdetail.FieldFeatures, field.TypeJSON, value)
		_node.Features = value
	}
	if value, ok := pdc.mutation.KeyAchievements(); ok {
		_spec.SetField(projectdetail.FieldKeyAchievements, field.TypeJSON, value)
		_node.KeyAchievements = value
	}
	if value, ok := pdc.mutation.ChallengesFaced(); ok {
		_spec.SetField(projectdetail.FieldChallengesFaced, field.TypeJSON, value)
		_node.ChallengesFaced = value
	}
	if value, ok := pdc.mutation.LessonsLearned(); ok {
		_spec.SetField(projectdetail.FieldLessonsLearned, field.TypeJSON, value)
		_node.LessonsLearned = value
	}
	if value, ok := pdc.mutation.TechnicalOverview(); ok {
		_spec.SetField(projectdetail.FieldTechnicalOverview, field.TypeString, value)
		_node.TechnicalOverview = value
	}
	if value, ok := pdc.mutation.InstallationInstructions(); ok {
		_spec.SetField(projectdetail.FieldInstallationInstructions, field.TypeString, value)
		_node.InstallationInstructions = value
	}
	if value, ok := pdc.mutation.UsageInstructions(); ok {
		_spec.SetField(projectdetail.FieldUsageInstructions, field.TypeString, value)
		_node.UsageInstructions = value
	}
	if value, ok := pdc.mutation.APIDocumentation(); ok {
		_spec.SetField(projectdetail.FieldAPIDocumentation, field.TypeString, value)
		_node.APIDocumentation = value
	}
	if value, ok := pdc.mutation.DeploymentNotes(); ok {
		_spec.SetField(projectdetail.FieldDeploymentNotes, field.TypeString, value)
		_node.DeploymentNotes = value
	}
	if value, ok := pdc.mutation.FutureEnhancements(); ok {
		_spec.SetField(projectdetail.FieldFutureEnhancements, field.TypeString, value)
		_node.FutureEnhancements = value
	}
	if value, ok := pdc.mutation.TeamMembers(); ok {
		_spec.SetField(projectdetail.FieldTeamMembers, field.TypeJSON, value)
		_node.TeamMembers = value
	}
	if value, ok := pdc.mutation.ProjectDuration(); ok {
		_spec.SetField(projectdetail.FieldProjectDuration, field.TypeString, value)
		_node.ProjectDuration = value
	}
	if value, ok := pdc.mutation.TargetAudience(); ok {
		_spec.SetField(projectdetail.FieldTargetAudience, field.TypeString, value)
		_node.TargetAudience = value
	}
	if value, ok := pdc.mutation.PerformanceMetrics(); ok {
		_spec.SetField(projectdetail.FieldPerformanceMetrics, field.TypeJSON, value)
		_node.PerformanceMetrics = value
	}
	if value, ok := pdc.mutation.TestingApproach(); ok {
		_spec.SetField(projectdetail.FieldTestingApproach, field.TypeJSON, value)
		_node.TestingApproach = value
	}
	if value, ok := pdc.mutation.CreatedAt(); ok {
		_spec.SetField(projectdetail.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := pdc.mutation.UpdatedAt(); ok {
		_spec.SetField(projectdetail.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := pdc.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   projectdetail.ProjectTable,
			Columns: []string{projectdetail.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.project_detail = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProjectDetailCreateBulk is the builder for creating many ProjectDetail entities in bulk.
type ProjectDetailCreateBulk struct {
	config
	err      error
	builders []*ProjectDetailCreate
}

// Save creates the ProjectDetail entities in the database.
func (pdcb *ProjectDetailCreateBulk) Save(ctx context.Context) ([]*ProjectDetail, error) {
	if pdcb.err != nil {
		return nil, pdcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pdcb.builders))
	nodes := make([]*ProjectDetail, len(pdcb.builders))
	mutators := make([]Mutator, len(pdcb.builders))
	for i := range pdcb.builders {
		func(i int, root context.Context) {
			builder := pdcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectDetailMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pdcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pdcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pdcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pdcb *ProjectDetailCreateBulk) SaveX(ctx context.Context) []*ProjectDetail {
	v, err := pdcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pdcb *ProjectDetailCreateBulk) Exec(ctx context.Context) error {
	_, err := pdcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pdcb *ProjectDetailCreateBulk) ExecX(ctx context.Context) {
	if err := pdcb.Exec(ctx); err != nil {
		panic(err)
	}
}
