// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"silan-backend/internal/ent/blogpost"
	"silan-backend/internal/ent/blogposttag"
	"silan-backend/internal/ent/blogtag"
	"silan-backend/internal/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// BlogPostTagQuery is the builder for querying BlogPostTag entities.
type BlogPostTagQuery struct {
	config
	ctx          *QueryContext
	order        []blogposttag.OrderOption
	inters       []Interceptor
	predicates   []predicate.BlogPostTag
	withBlogPost *BlogPostQuery
	withBlogTag  *BlogTagQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BlogPostTagQuery builder.
func (bptq *BlogPostTagQuery) Where(ps ...predicate.BlogPostTag) *BlogPostTagQuery {
	bptq.predicates = append(bptq.predicates, ps...)
	return bptq
}

// Limit the number of records to be returned by this query.
func (bptq *BlogPostTagQuery) Limit(limit int) *BlogPostTagQuery {
	bptq.ctx.Limit = &limit
	return bptq
}

// Offset to start from.
func (bptq *BlogPostTagQuery) Offset(offset int) *BlogPostTagQuery {
	bptq.ctx.Offset = &offset
	return bptq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bptq *BlogPostTagQuery) Unique(unique bool) *BlogPostTagQuery {
	bptq.ctx.Unique = &unique
	return bptq
}

// Order specifies how the records should be ordered.
func (bptq *BlogPostTagQuery) Order(o ...blogposttag.OrderOption) *BlogPostTagQuery {
	bptq.order = append(bptq.order, o...)
	return bptq
}

// QueryBlogPost chains the current query on the "blog_post" edge.
func (bptq *BlogPostTagQuery) QueryBlogPost() *BlogPostQuery {
	query := (&BlogPostClient{config: bptq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bptq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bptq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(blogposttag.Table, blogposttag.BlogPostColumn, selector),
			sqlgraph.To(blogpost.Table, blogpost.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, blogposttag.BlogPostTable, blogposttag.BlogPostColumn),
		)
		fromU = sqlgraph.SetNeighbors(bptq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBlogTag chains the current query on the "blog_tag" edge.
func (bptq *BlogPostTagQuery) QueryBlogTag() *BlogTagQuery {
	query := (&BlogTagClient{config: bptq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bptq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bptq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(blogposttag.Table, blogposttag.BlogTagColumn, selector),
			sqlgraph.To(blogtag.Table, blogtag.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, blogposttag.BlogTagTable, blogposttag.BlogTagColumn),
		)
		fromU = sqlgraph.SetNeighbors(bptq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BlogPostTag entity from the query.
// Returns a *NotFoundError when no BlogPostTag was found.
func (bptq *BlogPostTagQuery) First(ctx context.Context) (*BlogPostTag, error) {
	nodes, err := bptq.Limit(1).All(setContextOp(ctx, bptq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{blogposttag.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bptq *BlogPostTagQuery) FirstX(ctx context.Context) *BlogPostTag {
	node, err := bptq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// Only returns a single BlogPostTag entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BlogPostTag entity is found.
// Returns a *NotFoundError when no BlogPostTag entities are found.
func (bptq *BlogPostTagQuery) Only(ctx context.Context) (*BlogPostTag, error) {
	nodes, err := bptq.Limit(2).All(setContextOp(ctx, bptq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{blogposttag.Label}
	default:
		return nil, &NotSingularError{blogposttag.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bptq *BlogPostTagQuery) OnlyX(ctx context.Context) *BlogPostTag {
	node, err := bptq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// All executes the query and returns a list of BlogPostTags.
func (bptq *BlogPostTagQuery) All(ctx context.Context) ([]*BlogPostTag, error) {
	ctx = setContextOp(ctx, bptq.ctx, ent.OpQueryAll)
	if err := bptq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BlogPostTag, *BlogPostTagQuery]()
	return withInterceptors[[]*BlogPostTag](ctx, bptq, qr, bptq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bptq *BlogPostTagQuery) AllX(ctx context.Context) []*BlogPostTag {
	nodes, err := bptq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Count returns the count of the given query.
func (bptq *BlogPostTagQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bptq.ctx, ent.OpQueryCount)
	if err := bptq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bptq, querierCount[*BlogPostTagQuery](), bptq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bptq *BlogPostTagQuery) CountX(ctx context.Context) int {
	count, err := bptq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bptq *BlogPostTagQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bptq.ctx, ent.OpQueryExist)
	switch _, err := bptq.First(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bptq *BlogPostTagQuery) ExistX(ctx context.Context) bool {
	exist, err := bptq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BlogPostTagQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bptq *BlogPostTagQuery) Clone() *BlogPostTagQuery {
	if bptq == nil {
		return nil
	}
	return &BlogPostTagQuery{
		config:       bptq.config,
		ctx:          bptq.ctx.Clone(),
		order:        append([]blogposttag.OrderOption{}, bptq.order...),
		inters:       append([]Interceptor{}, bptq.inters...),
		predicates:   append([]predicate.BlogPostTag{}, bptq.predicates...),
		withBlogPost: bptq.withBlogPost.Clone(),
		withBlogTag:  bptq.withBlogTag.Clone(),
		// clone intermediate query.
		sql:  bptq.sql.Clone(),
		path: bptq.path,
	}
}

// WithBlogPost tells the query-builder to eager-load the nodes that are connected to
// the "blog_post" edge. The optional arguments are used to configure the query builder of the edge.
func (bptq *BlogPostTagQuery) WithBlogPost(opts ...func(*BlogPostQuery)) *BlogPostTagQuery {
	query := (&BlogPostClient{config: bptq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bptq.withBlogPost = query
	return bptq
}

// WithBlogTag tells the query-builder to eager-load the nodes that are connected to
// the "blog_tag" edge. The optional arguments are used to configure the query builder of the edge.
func (bptq *BlogPostTagQuery) WithBlogTag(opts ...func(*BlogTagQuery)) *BlogPostTagQuery {
	query := (&BlogTagClient{config: bptq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bptq.withBlogTag = query
	return bptq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		BlogPostID uuid.UUID `json:"blog_post_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BlogPostTag.Query().
//		GroupBy(blogposttag.FieldBlogPostID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bptq *BlogPostTagQuery) GroupBy(field string, fields ...string) *BlogPostTagGroupBy {
	bptq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BlogPostTagGroupBy{build: bptq}
	grbuild.flds = &bptq.ctx.Fields
	grbuild.label = blogposttag.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		BlogPostID uuid.UUID `json:"blog_post_id,omitempty"`
//	}
//
//	client.BlogPostTag.Query().
//		Select(blogposttag.FieldBlogPostID).
//		Scan(ctx, &v)
func (bptq *BlogPostTagQuery) Select(fields ...string) *BlogPostTagSelect {
	bptq.ctx.Fields = append(bptq.ctx.Fields, fields...)
	sbuild := &BlogPostTagSelect{BlogPostTagQuery: bptq}
	sbuild.label = blogposttag.Label
	sbuild.flds, sbuild.scan = &bptq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BlogPostTagSelect configured with the given aggregations.
func (bptq *BlogPostTagQuery) Aggregate(fns ...AggregateFunc) *BlogPostTagSelect {
	return bptq.Select().Aggregate(fns...)
}

func (bptq *BlogPostTagQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bptq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bptq); err != nil {
				return err
			}
		}
	}
	for _, f := range bptq.ctx.Fields {
		if !blogposttag.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bptq.path != nil {
		prev, err := bptq.path(ctx)
		if err != nil {
			return err
		}
		bptq.sql = prev
	}
	return nil
}

func (bptq *BlogPostTagQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BlogPostTag, error) {
	var (
		nodes       = []*BlogPostTag{}
		_spec       = bptq.querySpec()
		loadedTypes = [2]bool{
			bptq.withBlogPost != nil,
			bptq.withBlogTag != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BlogPostTag).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BlogPostTag{config: bptq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bptq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := bptq.withBlogPost; query != nil {
		if err := bptq.loadBlogPost(ctx, query, nodes, nil,
			func(n *BlogPostTag, e *BlogPost) { n.Edges.BlogPost = e }); err != nil {
			return nil, err
		}
	}
	if query := bptq.withBlogTag; query != nil {
		if err := bptq.loadBlogTag(ctx, query, nodes, nil,
			func(n *BlogPostTag, e *BlogTag) { n.Edges.BlogTag = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (bptq *BlogPostTagQuery) loadBlogPost(ctx context.Context, query *BlogPostQuery, nodes []*BlogPostTag, init func(*BlogPostTag), assign func(*BlogPostTag, *BlogPost)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*BlogPostTag)
	for i := range nodes {
		fk := nodes[i].BlogPostID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(blogpost.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "blog_post_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (bptq *BlogPostTagQuery) loadBlogTag(ctx context.Context, query *BlogTagQuery, nodes []*BlogPostTag, init func(*BlogPostTag), assign func(*BlogPostTag, *BlogTag)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*BlogPostTag)
	for i := range nodes {
		fk := nodes[i].BlogTagID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(blogtag.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "blog_tag_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (bptq *BlogPostTagQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bptq.querySpec()
	_spec.Unique = false
	_spec.Node.Columns = nil
	return sqlgraph.CountNodes(ctx, bptq.driver, _spec)
}

func (bptq *BlogPostTagQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(blogposttag.Table, blogposttag.Columns, nil)
	_spec.From = bptq.sql
	if unique := bptq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if bptq.path != nil {
		_spec.Unique = true
	}
	if fields := bptq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		for i := range fields {
			_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
		}
		if bptq.withBlogPost != nil {
			_spec.Node.AddColumnOnce(blogposttag.FieldBlogPostID)
		}
		if bptq.withBlogTag != nil {
			_spec.Node.AddColumnOnce(blogposttag.FieldBlogTagID)
		}
	}
	if ps := bptq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bptq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bptq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bptq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bptq *BlogPostTagQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bptq.driver.Dialect())
	t1 := builder.Table(blogposttag.Table)
	columns := bptq.ctx.Fields
	if len(columns) == 0 {
		columns = blogposttag.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bptq.sql != nil {
		selector = bptq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bptq.ctx.Unique != nil && *bptq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range bptq.predicates {
		p(selector)
	}
	for _, p := range bptq.order {
		p(selector)
	}
	if offset := bptq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bptq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BlogPostTagGroupBy is the group-by builder for BlogPostTag entities.
type BlogPostTagGroupBy struct {
	selector
	build *BlogPostTagQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bptgb *BlogPostTagGroupBy) Aggregate(fns ...AggregateFunc) *BlogPostTagGroupBy {
	bptgb.fns = append(bptgb.fns, fns...)
	return bptgb
}

// Scan applies the selector query and scans the result into the given value.
func (bptgb *BlogPostTagGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bptgb.build.ctx, ent.OpQueryGroupBy)
	if err := bptgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BlogPostTagQuery, *BlogPostTagGroupBy](ctx, bptgb.build, bptgb, bptgb.build.inters, v)
}

func (bptgb *BlogPostTagGroupBy) sqlScan(ctx context.Context, root *BlogPostTagQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bptgb.fns))
	for _, fn := range bptgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bptgb.flds)+len(bptgb.fns))
		for _, f := range *bptgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bptgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bptgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BlogPostTagSelect is the builder for selecting fields of BlogPostTag entities.
type BlogPostTagSelect struct {
	*BlogPostTagQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bpts *BlogPostTagSelect) Aggregate(fns ...AggregateFunc) *BlogPostTagSelect {
	bpts.fns = append(bpts.fns, fns...)
	return bpts
}

// Scan applies the selector query and scans the result into the given value.
func (bpts *BlogPostTagSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bpts.ctx, ent.OpQuerySelect)
	if err := bpts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BlogPostTagQuery, *BlogPostTagSelect](ctx, bpts.BlogPostTagQuery, bpts, bpts.inters, v)
}

func (bpts *BlogPostTagSelect) sqlScan(ctx context.Context, root *BlogPostTagQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bpts.fns))
	for _, fn := range bpts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bpts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bpts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
