# Local Silan Configuration
# This file contains local-specific settings that override workspace defaults

# Local Development Settings
development:
  debug_mode: true
  verbose_logging: true
  auto_save: true
  watch_file_changes: false

# CLI Preferences
cli:
  default_editor: "code"  # VS Code
  preferred_terminal: "zsh"
  show_progress_bars: true
  colored_output: true
  confirm_destructive_operations: true

# Cache Settings
cache:
  enabled: true
  size_limit: "500MB"
  cleanup_frequency: "daily"
  aggressive_cleanup: false

# Logging Preferences
logging:
  level: "INFO"
  console_output: true
  file_output: true
  show_timestamps: true
  include_stack_traces: false

# Template Preferences
templates:
  auto_fill_author: true
  default_author: "Silan Hu"
  default_email: "silan.hu@u.nus.edu"
  default_license: "MIT"
  preferred_languages: ["en", "zh"]

# Analytics Settings
analytics:
  enabled: true
  collection_level: "full"  # minimal, standard, full
  share_anonymous_usage: false
  generate_insights: true
  weekly_reports: true

# Git Integration
git:
  auto_commit: false
  commit_message_template: "feat: {action} {content_type} '{title}'"
  auto_push: false
  branch_naming: "feature/{content-type}-{slug}"

# Performance Settings
performance:
  parallel_operations: true
  max_workers: 4
  memory_limit: "2GB"
  timeout_seconds: 300

# Backup Settings
backup:
  auto_backup: true
  backup_frequency: "daily"
  keep_backups: 7
  backup_location: ".silan/backups"
  compress_backups: true

# UI/UX Preferences
ui:
  theme: "auto"  # light, dark, auto
  animation_speed: "normal"  # slow, normal, fast, off
  sound_effects: false
  notifications: true

# Content Preferences
content:
  default_language: "en"
  auto_generate_ids: true
  slug_format: "kebab-case"
  date_format: "YYYY-MM-DD"
  time_format: "24h"

# Export Settings
export:
  default_format: "markdown"
  include_metadata: true
  include_assets: true
  preserve_structure: true

# Privacy Settings
privacy:
  anonymize_personal_data: false
  exclude_sensitive_fields: true
  data_retention_days: 365
  
# User Preferences
user:
  workspace_startup_action: "health_check"  # none, health_check, full_analysis
  auto_update_check: true
  beta_features: true
  telemetry: false

# Local Paths
paths:
  temp_directory: ".silan/temp"
  cache_directory: ".silan/cache"
  logs_directory: ".silan/logs"
  backups_directory: ".silan/backups"

# Editor Integration
editor:
  vscode:
    auto_open_projects: true
    recommended_extensions: true
    workspace_settings: true
  
# Last Modified
meta:
  last_modified: "2024-12-19T21:00:00Z"
  config_version: "2.0.0"
  created_by: "Silan Workspace Manager" 