// Code generated by ent, DO NOT EDIT.

package blogseries

import (
	"silan-backend/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldEQ(FieldUserID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldEQ(FieldTitle, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldEQ(FieldSlug, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldEQ(FieldDescription, v))
}

// FeaturedImageURL applies equality check predicate on the "featured_image_url" field. It's identical to FeaturedImageURLEQ.
func FeaturedImageURL(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldEQ(FieldFeaturedImageURL, v))
}

// PostCount applies equality check predicate on the "post_count" field. It's identical to PostCountEQ.
func PostCount(v int) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldEQ(FieldPostCount, v))
}

// IsCompleted applies equality check predicate on the "is_completed" field. It's identical to IsCompletedEQ.
func IsCompleted(v bool) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldEQ(FieldIsCompleted, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldLTE(FieldUserID, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldContainsFold(FieldTitle, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldContainsFold(FieldSlug, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldContainsFold(FieldDescription, v))
}

// FeaturedImageURLEQ applies the EQ predicate on the "featured_image_url" field.
func FeaturedImageURLEQ(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldEQ(FieldFeaturedImageURL, v))
}

// FeaturedImageURLNEQ applies the NEQ predicate on the "featured_image_url" field.
func FeaturedImageURLNEQ(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldNEQ(FieldFeaturedImageURL, v))
}

// FeaturedImageURLIn applies the In predicate on the "featured_image_url" field.
func FeaturedImageURLIn(vs ...string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldIn(FieldFeaturedImageURL, vs...))
}

// FeaturedImageURLNotIn applies the NotIn predicate on the "featured_image_url" field.
func FeaturedImageURLNotIn(vs ...string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldNotIn(FieldFeaturedImageURL, vs...))
}

// FeaturedImageURLGT applies the GT predicate on the "featured_image_url" field.
func FeaturedImageURLGT(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldGT(FieldFeaturedImageURL, v))
}

// FeaturedImageURLGTE applies the GTE predicate on the "featured_image_url" field.
func FeaturedImageURLGTE(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldGTE(FieldFeaturedImageURL, v))
}

// FeaturedImageURLLT applies the LT predicate on the "featured_image_url" field.
func FeaturedImageURLLT(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldLT(FieldFeaturedImageURL, v))
}

// FeaturedImageURLLTE applies the LTE predicate on the "featured_image_url" field.
func FeaturedImageURLLTE(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldLTE(FieldFeaturedImageURL, v))
}

// FeaturedImageURLContains applies the Contains predicate on the "featured_image_url" field.
func FeaturedImageURLContains(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldContains(FieldFeaturedImageURL, v))
}

// FeaturedImageURLHasPrefix applies the HasPrefix predicate on the "featured_image_url" field.
func FeaturedImageURLHasPrefix(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldHasPrefix(FieldFeaturedImageURL, v))
}

// FeaturedImageURLHasSuffix applies the HasSuffix predicate on the "featured_image_url" field.
func FeaturedImageURLHasSuffix(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldHasSuffix(FieldFeaturedImageURL, v))
}

// FeaturedImageURLIsNil applies the IsNil predicate on the "featured_image_url" field.
func FeaturedImageURLIsNil() predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldIsNull(FieldFeaturedImageURL))
}

// FeaturedImageURLNotNil applies the NotNil predicate on the "featured_image_url" field.
func FeaturedImageURLNotNil() predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldNotNull(FieldFeaturedImageURL))
}

// FeaturedImageURLEqualFold applies the EqualFold predicate on the "featured_image_url" field.
func FeaturedImageURLEqualFold(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldEqualFold(FieldFeaturedImageURL, v))
}

// FeaturedImageURLContainsFold applies the ContainsFold predicate on the "featured_image_url" field.
func FeaturedImageURLContainsFold(v string) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldContainsFold(FieldFeaturedImageURL, v))
}

// PostCountEQ applies the EQ predicate on the "post_count" field.
func PostCountEQ(v int) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldEQ(FieldPostCount, v))
}

// PostCountNEQ applies the NEQ predicate on the "post_count" field.
func PostCountNEQ(v int) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldNEQ(FieldPostCount, v))
}

// PostCountIn applies the In predicate on the "post_count" field.
func PostCountIn(vs ...int) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldIn(FieldPostCount, vs...))
}

// PostCountNotIn applies the NotIn predicate on the "post_count" field.
func PostCountNotIn(vs ...int) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldNotIn(FieldPostCount, vs...))
}

// PostCountGT applies the GT predicate on the "post_count" field.
func PostCountGT(v int) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldGT(FieldPostCount, v))
}

// PostCountGTE applies the GTE predicate on the "post_count" field.
func PostCountGTE(v int) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldGTE(FieldPostCount, v))
}

// PostCountLT applies the LT predicate on the "post_count" field.
func PostCountLT(v int) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldLT(FieldPostCount, v))
}

// PostCountLTE applies the LTE predicate on the "post_count" field.
func PostCountLTE(v int) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldLTE(FieldPostCount, v))
}

// IsCompletedEQ applies the EQ predicate on the "is_completed" field.
func IsCompletedEQ(v bool) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldEQ(FieldIsCompleted, v))
}

// IsCompletedNEQ applies the NEQ predicate on the "is_completed" field.
func IsCompletedNEQ(v bool) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldNEQ(FieldIsCompleted, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BlogSeries {
	return predicate.BlogSeries(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.BlogSeries {
	return predicate.BlogSeries(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.BlogSeries {
	return predicate.BlogSeries(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBlogPosts applies the HasEdge predicate on the "blog_posts" edge.
func HasBlogPosts() predicate.BlogSeries {
	return predicate.BlogSeries(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BlogPostsTable, BlogPostsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBlogPostsWith applies the HasEdge predicate on the "blog_posts" edge with a given conditions (other predicates).
func HasBlogPostsWith(preds ...predicate.BlogPost) predicate.BlogSeries {
	return predicate.BlogSeries(func(s *sql.Selector) {
		step := newBlogPostsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BlogSeries) predicate.BlogSeries {
	return predicate.BlogSeries(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BlogSeries) predicate.BlogSeries {
	return predicate.BlogSeries(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BlogSeries) predicate.BlogSeries {
	return predicate.BlogSeries(sql.NotPredicates(p))
}
