# Silan Workspace Configuration
# Modern workspace management system for AI-powered portfolio
workspace:
  name: "API Test Portfolio"
  description: "Test project for API data synchronization and portfolio management"
  version: "2.0.0"
  created_date: "2024-01-01"
  last_modified: "2024-12-19"
  workspace_type: "portfolio"
  
  # Workspace owner
  owner:
    username: "admin"
    email: "silan.hu@u.nus.edu"
    first_name: "Silan"
    last_name: "Hu"
    bio: "Master student at NUS, Singapore"
    profile_image: ""

# Database Configuration
database:
  type: "sqlite"
  sqlite:
    path: "portfolio.db"
  settings:
    create_tables: true
    backup_before_sync: true
    auto_migrate: true

# Directory Structure
directories:
  content: "content"
  templates: "templates"
  cache: ".silan/cache"
  logs: ".silan/logs"
  exports: "exports"
  backups: "backups"

# Content Types Configuration  
content_types:
  projects:
    enabled: true
    structure: "folder"  # folder-based projects
    path: "content/projects"
    template: "project"
    auto_create_folders: ["assets", "notes", "research"]
    required_fields: ["title", "description", "technologies"]
    categories: ["web-app", "research", "mobile-app", "ai-tool", "data-analysis"]
    
  ideas:
    enabled: true
    structure: "folder"  # folder-based ideas
    path: "content/ideas"
    template: "idea"
    auto_create_folders: ["research", "notes", "experiments", "references", "prototypes", "assets"]
    required_fields: ["title", "description", "field"]
    categories: ["ai", "research", "development", "innovation", "optimization"]
    
  updates:
    enabled: true
    structure: "file"  # individual MD files organized by date
    path: "content/updates"
    template: "update"
    organization: "date-based"  # YYYY/MM/YYYY-MM-DD-title.md
    required_fields: ["title", "content"]
    types: ["milestone", "achievement", "progress", "announcement"]
    
  blog:
    enabled: true
    structure: "file"
    path: "content/blog"
    subfolders: ["posts", "drafts"]
    template: "blog"
    required_fields: ["title", "excerpt", "content"]
    categories: ["tech", "tutorial", "research", "opinion"]
    
  resume:
    enabled: true
    structure: "file"
    path: "content/resume"
    template: "resume"
    required_fields: ["name", "title", "contact"]

# Language Configuration
languages:
  default: "en"
  supported:
    - code: "en"
      name: "English"
      native_name: "English"
    - code: "zh"
      name: "Chinese"
      native_name: "中文"

# Workspace Settings
settings:
  auto_sync: true
  watch_files: false
  auto_backup: true
  backup_frequency: "daily"
  backup_retention_days: 30
  
  # Content Processing
  process_markdown: true
  generate_html: true
  extract_metadata: true
  validate_frontmatter: true
  
  # File Handling
  ignore_patterns:
    - "*.tmp"
    - "*.bak"
    - ".DS_Store"
    - "Thumbs.db"
    - "node_modules/"
    - ".git/"
  
  # Logging
  log_level: "info"
  log_file: ".silan/logs/workspace.log"

# API Configuration
api:
  enabled: true
  host: "localhost"
  port: 8000
  cors_origins: 
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
  rate_limiting: true
  authentication: true

# Development Settings
development:
  debug: true
  hot_reload: true
  test_data: true
  mock_external_apis: false

# Export Settings
export:
  formats: ["json", "yaml", "markdown", "pdf"]
  output_dir: "exports"
  include_metadata: true
  compress_output: false

# Performance Settings
performance:
  cache_enabled: true
  cache_ttl: 3600
  max_file_size: "10MB"
  batch_size: 100
  query_timeout: 30

# Security Settings
security:
  password_hashing: "bcrypt"
  session_timeout: 3600
  max_login_attempts: 5
  lockout_duration: 900
  require_strong_passwords: true

# Workspace Health Tracking
health:
  last_check: "2024-12-19"
  score: 8.5
  issues: []
  recommendations:
    - "Add more project documentation"
    - "Create regular update schedule"
    - "Expand idea research materials"

# Activity Tracking
activity:
  last_activity: "2024-12-19"
  total_projects: 3
  total_ideas: 2
  total_updates: 0
  total_blog_posts: 2
  recent_activities: []

# Integrations
integrations:
  github:
    enabled: false
    token: ""
    repository: ""
    auto_sync: false
    
  notion:
    enabled: false
    token: ""
    database_id: "" 