project_name: "API Test Portfolio"
description: "Test project for API data synchronization and portfolio management"
version: "1.0.0"
language: "en"

# Author/User Configuration
user:
  username: "admin"
  email: "admin@example.com"
  password: "secure_password_2024"
  first_name: "Portfolio"
  last_name: "Admin"
  bio: "Portfolio administrator and content manager"

# Database configuration
database:
  # Primary database (choose one)
  type: "sqlite"  # Options: sqlite, mysql, postgresql
  
  # SQLite configuration
  sqlite:
    path: "portfolio.db"
    
  # MySQL configuration (uncomment if using MySQL)
  # mysql:
  #   host: "localhost"
  #   port: 3306
  #   database: "silan_portfolio"
  #   user: "root"
  #   password: ""
  #   charset: "utf8mb4"
  
  # PostgreSQL configuration (uncomment if using PostgreSQL)
  # postgresql:
  #   host: "localhost"
  #   port: 5432
  #   database: "silan_portfolio"
  #   user: "postgres"
  #   password: ""

# Content directories
content:
  base_dir: "content"
  resume_dir: "content/resume"
  projects_dir: "content/projects"
  blog_dir: "content/blog"
  ideas_dir: "content/ideas"
  plans_dir: "content/plans"
  research_dir: "content/research"
  education_dir: "content/education"
  experience_dir: "content/experience"

# Synchronization settings
sync:
  # Database sync options
  create_tables: true
  backup_before_sync: true
  auto_migrate: true
  
  # Content processing
  process_markdown: true
  generate_html: true
  extract_metadata: true
  validate_frontmatter: true
  
  # File handling
  watch_files: false
  ignore_patterns:
    - "*.tmp"
    - "*.bak"
    - ".DS_Store"
    - "Thumbs.db"
  
  # Logging
  log_level: "info"  # Options: debug, info, warning, error
  log_file: "sync.log"

# Language and localization
languages:
  default: "en"
  supported:
    - code: "en"
      name: "English"
      native_name: "English"
    - code: "zh"
      name: "Chinese"
      native_name: "中文"
    - code: "es"
      name: "Spanish"
      native_name: "Español"

# Content types configuration
content_types:
  resume:
    enabled: true
    template: "resume_template.md"
    required_fields: ["name", "title", "contact"]
    
  projects:
    enabled: true
    template: "project_template.md"
    required_fields: ["title", "description", "technologies"]
    categories: ["web", "mobile", "ai", "data", "other"]
    
  blog:
    enabled: true
    template: "blog_template.md"
    required_fields: ["title", "excerpt", "content"]
    categories: ["tech", "tutorial", "opinion", "news"]
    
  ideas:
    enabled: true
    template: "idea_template.md"
    required_fields: ["title", "description"]
    priority_levels: ["low", "medium", "high", "urgent"]
    
  plans:
    enabled: true
    template: "plan_template.md"
    required_fields: ["title", "objectives", "timeline"]
    
  research:
    enabled: true
    template: "research_template.md"
    required_fields: ["title", "abstract", "methodology"]
    
  education:
    enabled: true
    template: "education_template.md"
    required_fields: ["institution", "degree", "field"]
    
  experience:
    enabled: true
    template: "experience_template.md"
    required_fields: ["company", "position", "start_date"]

# API configuration
api:
  enabled: true
  host: "localhost"
  port: 8000
  cors_origins: ["http://localhost:3000", "http://127.0.0.1:3000"]
  rate_limiting: true
  authentication: true

# Export settings
export:
  formats: ["json", "yaml", "csv", "pdf"]
  output_dir: "exports"
  include_metadata: true
  compress_output: false

# Development settings
development:
  debug: true
  hot_reload: true
  test_data: true
  mock_external_apis: false

# Production settings
production:
  debug: false
  compression: true
  caching: true
  security_headers: true
  ssl_required: false

# Backup configuration
backup:
  enabled: true
  frequency: "daily"  # Options: hourly, daily, weekly, monthly
  retention_days: 30
  backup_dir: "backups"
  include_database: true
  include_content: true
  compress_backups: true

# Integration settings
integrations:
  github:
    enabled: false
    token: ""
    repository: ""
    auto_sync: false
    
  notion:
    enabled: false
    token: ""
    database_id: ""
    
  airtable:
    enabled: false
    api_key: ""
    base_id: ""
    
  google_drive:
    enabled: false
    credentials_file: ""
    folder_id: ""

# Security settings
security:
  password_hashing: "bcrypt"
  session_timeout: 3600  # seconds
  max_login_attempts: 5
  lockout_duration: 900  # seconds
  require_strong_passwords: true
  enable_2fa: false

# Performance settings
performance:
  cache_enabled: true
  cache_ttl: 3600  # seconds
  max_file_size: "10MB"
  batch_size: 100
  connection_pool_size: 10
  query_timeout: 30  # seconds

# Monitoring and analytics
monitoring:
  enabled: true
  metrics_collection: true
  error_tracking: true
  performance_monitoring: true
  log_retention_days: 90